name = "onetime-tohoku-ts-group" # あなたのWorkerに分かりやすい名前を付けましょう
main = "functions/verify-captcha.ts" # ★ここを修正！Workerのメインコードのパスを指定
compatibility_date = "2025-07-21"    # 今日の日付（2025年7月21日）に更新
workers_dev = true

# --- [site]セクションも忘れずに！ ---
[site]
bucket = "./public" # 静的ファイルが置かれているディレクトリを指定
# --- ここまで [site]セクション ---

[vars]
# 環境変数が必要な場合はここに記述
